version: '3.8'

services:
  backend:
    build:
      context: ./inventory-system
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=inventory_db
      - JWT_SECRET=your-super-secret-key-here
    volumes:
      - ./inventory-system:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 